<h1>Room Adverts</h1>
<table 
	class="table table-condensed table-hover table-striped"
	id="advertTable" 
>
	<thead>
		<tr>
			<th></th>
			<th>ID</th>
			<th>Title</th>
			<th>City</th>
			<th>Picture</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php	foreach ($adverts as $advert) {
?>
			<tr>
				<td>
					<input 
						type="checkbox" 
						class="select-advert-row" 
						data-id="<?= $advert->getID(); ?>" 
					/>
				</td>
				<td><?= $advert->getID(); ?></td>
				<td><?= $advert->getTitle(); ?></td>
				<td><?= $advert->getCity(); ?></td>
				<td>
					<a 
						href="<?= $advert->getPicture(); ?>"
						target="_blank"
					>
						<img 
							src="<?= $advert->getPicture(); ?>"
							alt="<?= $advert->getTitle(); ?>"
							width="50"
							height="50"
						/>
					</a>
				</td>
				<td>
					<a 
						href="<?= $advert->getUrl(); ?>"
						class="btn btn-sm btn-primary"
						target="_blank"
					>
						Visit
					</a>
				</td>
				
				
			</tr>
<?php	}
?>
	</tbody>
</table>